### ISSUE TITLE
Performanceprobleme bei Start

### ISSUE THREAD

**Issue by adams2302** [adams2302/dvd-rental#5]
Zwischen Start des Python-Service Containers und Ausgabe der Aufgaben vergehen bei mir teilweise mehr als zwei Minuten. Warum ist das so? (Ist das nur bei mir, mit recht kleinem RAM?)
An unserem Skript kann es mE nicht liegen, da die Ausgabe "Python Skript startet..." auch zeitverzögert erschient. Alle weiteren Ausgaben werden unmittelbar gedruckt. 
Es scheint also, dass der Ausführungszeitpunkt des Skripts zeitverzögert ist.

**Comment by knieling23** [comment]
Zu beginn werden die Container removed und im Anschluss neu erstellt. Das kostet Zeit und ist so vorgesehen, damit der Prof das auch ausführen kann und gleiche Ausgangsbedingungen hat. Nach dem Kommentar "Skript startet" ist bei mir die Laufzeit noch im Rahmen. Wenn du möchtest können wir die Laufzeit auch tracken und vergleichen ob es an der Hardware liegt.

**Comment by knieling23** [comment]
Ergebnis für das Verbinden + main():
2024-11-13 10:43:06 Gesamtlaufzeit des Skripts: 91.98 Sekunden

**Comment by adams2302** [comment]
Danke fürs Checken!
Ergebnis bei mir:
2024-11-13 14:07:07 Gesamtlaufzeit des Skripts: 123.39 Sekunden
Scheint wohl tatsächlich an meinem alten MacBook zu liegen :D
